### ISSUE TITLE
missing metadata

### ISSUE THREAD

**Issue by bjozet** [chef-cookbooks/compat_resource#20]
metadata.rb lacks maintainer and maintainer_email, please add the properties.

I'm get the following error when trying to upload the cookbook to chef server.

`Uploading compat_resource [12.5.14]
ERROR: The data in your request was invalid
Response: Field 'metadata.maintainer' invalid`

Although I can't find the chef-documentation for metadata.rb that says that this is a required property. I might be missing something.

**Comment by lamont-granquist** [comment]
closed by #21

**Comment by sadaf2605** [comment]
On starter cookook, when I tried to upload it I also get sae error message:
```
Uploading poise-python [0.0.0]
Uploading starter      [1.0.0]
ERROR: The data in your request was invalid
```

**Comment by thommay** [comment]
@sadaf2605:
At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
