### ISSUE TITLE
Recipe Compile Error in /var/chef/cache/cookbooks/compat_resource/libraries/autoload.rb

### ISSUE THREAD

**Issue by sarikav1986** [chef-cookbooks/compat_resource#69]
We are running on Chef 11.8.2 and getting below error. We can't upgrade chef version due to some internal reasons. Can you please suggest me compatible version which can work with Chef 11.8.2 ?

Recipe Compile Error in /var/chef/cache/cookbooks/compat_resource/libraries/autoload.rb
This resource is written with Chef 12.5 custom resources, and requires at least Chef 12.0 used with the compat_resource cookbook, it will not work with Chef 11.x clients, and those users must pin their cookbooks to older versions or upgrade.

**Comment by gbish** [comment]
@sarikav1986 I ran into a similar issue. The main culprits for me were `apt` and `build-essential`.

Make sure they're at versions prior to the `compat_resource` inclusion, so in my case, `'apt', '~> 3.0.0'` and `'build-essential', '~> 3.2.0'`. `ohai` may also be causing a problem so check on that too.

If those aren't you're specific problem cookbooks, just compare your run list against the list of cookbooks that have it as a dependency. It might take a while, but it's the only sure fire way I know.

As an aside, make sure you change the version on your envrionment for the relevant cookbooks if you have them locked down. I forgot about this, and had to scratch my head for a while trying to figure out what the issue was!

**Comment by sarikav1986** [comment]
@gbish Thanks a lot for help, Yes I figured that out latter and was able to fix by fixing versions of 'apt' and 'build-essential'.

**Comment by gomteshhatginecognologix** [comment]
Even facing same problem, Is something wrong

cookbook 'jenkins', '= 2.4.0'
cookbook 'iptables', '= 1.1.0'
cookbook 'apt', '~> 3.0.0'
cookbook 'build-essential', '~> 3.2.0'
