### ISSUE TITLE
Don't patch chef version > 12.5

### ISSUE THREAD

**Issue by kamaradclimber** [chef-cookbooks/compat_resource#75]
### Cookbook version
12.10.6

### Chef-client version
12.8.1

### Scenario:
- Trying to run chefspec on a cookbook that has dependencies on compat_resource
- no Gemfile.lock nor Berksfile.lock
- spec fails because:
```
#<RuntimeError: compat_resource gem version 12.10.7 was loaded as a gem before compat_resource cookbo... gem version, update the gem to the cookbook version, or uninstall / stop loading the gem so early.>
```

### Expected Result:

Proper convergence.

### Suggested solution

Don't try to patch chef 12.8.1since it has all features.

**Comment by kamaradclimber** [comment]
NB: I might not understand well the need for for this cookbook when running chef 12.5 and above.

**Comment by tas50** [comment]
@kamaradclimber 12.5 introduced custom resources, but we've continued to make refinements (mostly bugfixes) since then. Those changes are packages up after each chef release and we ship a new version of this cookbook. By running compat_resource on 12.8 you're basically backporting a bug fixed custom resource implementation to 12.8. That was the desired workflow of this cookbook so it's something we'd like to keep.

I'm also a bit confused on how the cookbook is failing with compat_resource included. We require compat_resource in a large number of our cookbooks and chefspec runs fine. We're running the latest chefspec and the latest compat_resource. Can you make sure you have the latest version of everything in the toolchain?

**Comment by kamaradclimber** [comment]
thanks @tas50 for your answer.

About this issue: we don't lock gems nor cookbooks in our CI. On July 18th, our CI ran with the 12.10.7 version even though the latest gem available was 12.10.6. This made compat_resource cookbook raise an exception (for good reasons).
It might be due to our rubygems proxy/cache.

This leads me to think about the role of compat_resource in our organization. Here is how I see it:
- compat_resource brings new features/bugfixes to early chef version by patching core chef code
- this leads to large spectrum issues such as #66 which are desastrous for us (we use before notifications to execute some locking around critical resource convergence)
- since many community cookbooks depends on compat_resource, the code is loaded on nearly all our nodes
- we run recent chef versions (12.5.1 and 12.8.1 depending on teams) and want to rely on chef-client updates to fix chef-client bugs

Of course this heavily depends on our organization and the way we work, I understand others might have different needs/constraints.

I'd like to get your input on how we could proceed to prevent any chef-client patch.

**Comment by brandocorp** [comment]
So here's a more concrete example. I have, as of this writing, the latest `chefdk-0.15.16` installed on my laptop and I'm trying to run my ChefSpec tests against a cookbook I'm writing. `my_cookbook` depends on `build-essential` which depends on `compat_resources` >= 12.10.

When I resolve my dependencies with Berkshelf, I'm pulling in 12.10.7 because that's, as of this writing, the latest available version of the cookbook. I'm not personally using `compat_resources` so until the error I wasn't fully aware it was included in my run list. Since I'm using chefdk, I have `compat_resources` pre-installed at 12.10.6. When I run my tests, 12.10.6 is loaded because it was pre-installed, and the `compat_resources` cookbook fails because it's a newer version than my chefdk installation.

We're seeing a similar issue on our build machine where different pinned run lists end up having different versions of `compat_resources` which all seemingly conflict with each other.

**Comment by lamont-granquist** [comment]
So yeah, to be definitive:

- we're backporting more than just custom resources in this cookbook now.
- if you look at #80 tom is adding apt_update and apt_repository core LWRPs so that we can use those in community cookbooks
- i've also backported some of the resource collection / notification changes from something like 12.10 (which it looks like broke :before and we need to fix)

This is all being done so that similarly to custom resources we can use those feature in community cookbooks while still supporting 12.old versions of chef-client.  Otherwise we're trapped in a situation where we can't use anything new that we write for another year or two until everyone upgrades their chef clients.

So, the suggestion to not do anything on new versions of chef-client won't fly at all.  As written the title of this is just a wontfix.

I'm still trying to digest the actual issue that you're seeing though, but i want to be very clear that your proposed solution is wrong.

**Comment by lamont-granquist** [comment]
so @kamaradclimber it seems like mostly your problems sum up to the fact that we need to fix #66 which i'd agree with.

**Comment by lamont-granquist** [comment]
@brandocorp that seems to be a legit problem, and I kind of hate the way we're trying to use this as a gem and a cookbook and that gets into fights.  Your problem is a good example of that.  I'd be more inclined to tackle and issue which was to completely back out the usage of this cookbook as a gem like that and possibly remove that functionality.  I think it has become tightly coupled with cheffish and/or chef-provisioning though and that would need to get untangled.

**Comment by lamont-granquist** [comment]
closing in favor of #66 and #81

**Comment by kamaradclimber** [comment]
thanks @lamont-granquist for your feedback.

Since my issue is more the fact that my organization does not want to one cookbook to patch chef core feature, we will solve this internally by using an empty fork of this cookbook.
